# Generated by Django 3.2.2 on 2021-12-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.CharField(max_length=100)),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idCarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.carrocompras')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosVendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idCarro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.carrocompras')),
            ],
        ),
    ]
