version: '3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'servicio'
       MYSQL_USER: 'fernando'
       MYSQL_PASSWORD: 'laclave'
       MYSQL_ROOT_PASSWORD: 'laclave'
  servicio:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb