# Generated by Django 3.2.2 on 2021-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fechaVenta',
            field=models.CharField(max_length=100),
        ),
    ]
